import type { NextPage } from "next";
import Head from "next/head";
// import { Details } from "board-lukuku";
import dynamic from "next/dynamic";
const DynamicComponent = dynamic(
  () => import("board-lukuku/lib/esm/index").then((mod) => mod.RichEditor),
  { ssr: false, loading: () => <p>...</p> }
);

const Home: NextPage = () => {
  const handleEditorContent = (content: any) => {
    console.log("content", content);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DynamicComponent handleContent={handleEditorContent} />
      </main>
    </div>
  );
};

export default Home;
