import type { NextPage } from "next";
import Head from "next/head";
import { Details } from "board";

const Home: NextPage = () => {
  console.log(typeof Details);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Hello World</h2>
      </main>
    </div>
  );
};

export default Home;
